resources/README.md
Spelling mistake in the googleapis/resources/readme.md file.
[ spececific --> Specific ]
=> Spelling mistake 🙂

googleapis_auth/CHANGELOG.md, googleapis_auth/README.md, googleapis_auth/pubspec.yaml
- Small readme tweaks
- Prepare to release null-safe preview 1.0.0-nullsafety.0
=> auth null safe

.github/workflows/dart.yml, discoveryapis_commons/CHANGELOG.md, discoveryapis_commons/lib/_discoveryapis_commons.dart, discoveryapis_commons/lib/src/requests.dart, discoveryapis_commons/pubspec.yaml, discoveryapis_generator/pubspec.yaml, generator/lib/googleapis_generator.dart, generator/mono_pkg.yaml, generator/pubspec.lock, generator/pubspec.yaml, generator/tool/config_delta.dart, googleapis_auth/CHANGELOG.md, googleapis_auth/pubspec.yaml
- commons: include fixes from dart-archive/discoveryapis_commons#536b80ba3
- Prepare for stable, null-safe versions of auth and common
=> googleapis auth stable

discoveryapis_generator/lib/src/generated_googleapis/discovery/v1.dart, generator/lib/googleapis_generator.dart, generator/lib/src/client.dart
Wire up a custom HTTP client that sets the correct request headers
=> Use the latest generated discovery API

.github/workflows/dart.yml, _test/expected_identical.dart, _test/expected_nonidentical.dart, _test/mono_pkg.yaml, _test/pubspec.yaml, _test/rest/toyapi.json, _test_package/lib/toyapi/0_1.dart, _test_package/mono_pkg.yaml, _test_package/pubspec.yaml, _test_package/test/toyapi/0_1_test.dart, discoveryapis_commons/CHANGELOG.md, discoveryapis_commons/lib/src/clients.dart, discoveryapis_commons/lib/src/requests.dart, discoveryapis_commons/mono_pkg.yaml, discoveryapis_commons/test/discoveryapis_commons_test.dart, discoveryapis_generator/example/dartservices.dart, discoveryapis_generator/lib/src/apis_package_generator.dart, discoveryapis_generator/lib/src/dart_resources.dart, discoveryapis_generator/lib/src/pubspec.dart, discoveryapis_generator/mono_pkg.yaml, discoveryapis_generator/pubspec.yaml, generator/mono_pkg.yaml, googleapis_auth/mono_pkg.yaml
Fix non-standard field names
Cleanup a lot of the async logic
=> Breaking change to _discoveryapis_commmons

discoveryapis_commons/lib/src/clients.dart, discoveryapis_commons/lib/src/request_headers.dart, discoveryapis_commons/lib/src/version_fallback.dart, generator/lib/src/client.dart
Also share header definition with generator code
=> Update request headers to ensure proper telemetry

config.yaml, generated/googleapis/pubspec.yaml, generated/googleapis_beta/pubspec.yaml
Fixes https://github.com/dart-lang/googleapis/issues/100
Also run CI on stable
=> Fix repository URL

.github/workflows/dart.yml, discoveryapis_commons/lib/_discoveryapis_commons.dart, discoveryapis_commons/lib/src/api_requester.dart, discoveryapis_commons/lib/src/requests.dart, discoveryapis_commons/lib/src/utils.dart, discoveryapis_commons/test/discoveryapis_commons_test.dart, test_integration/mono_pkg.yaml, test_integration/pubspec.yaml, test_integration/test/integration_test.dart
- commons: more cleanup
- Add an integration test to validate upload/download logic
=> integration test

discoveryapis_generator/CHANGELOG.md, discoveryapis_generator/README.md, discoveryapis_generator/pubspec.yaml
Fixes https://github.com/dart-lang/googleapis/issues/188
=> Publish v1 of discoveryapis_generator

googleapis_auth/CHANGELOG.md, googleapis_auth/lib/auth_io.dart, googleapis_auth/lib/src/adc_utils.dart, googleapis_auth/lib/src/metadata_server_client.dart, googleapis_auth/lib/src/oauth2_flows/base_flow.dart, googleapis_auth/lib/src/oauth2_flows/jwt.dart, googleapis_auth/lib/src/oauth2_flows/metadata_server.dart, googleapis_auth/lib/src/service_account_client.dart, googleapis_auth/pubspec.yaml
2 classes -> 1
Unified logic for created a Client from a "Flow"
=> DRY'd up shared logic between service account and metadata server flows

googleapis_auth/CHANGELOG.md, googleapis_auth/lib/src/oauth2_flows/auth_code.dart, googleapis_auth/pubspec.yaml
Fixes https://github.com/dart-lang/googleapis/issues/194
=> Fix an error when doing OAUTH code exchanged with an undefined secret

googleapis_auth/CHANGELOG.md, googleapis_auth/lib/auth_browser.dart, googleapis_auth/lib/auth_io.dart, googleapis_auth/lib/googleapis_auth.dart, googleapis_auth/lib/src/auth_functions.dart
Fixes https://github.com/dart-lang/googleapis/issues/198
=> export `clientViaApiKey` from `googleapis_auth.dart`

googleapis_auth/lib/src/auth_functions.dart, googleapis_auth/lib/src/oauth2_flows/auth_code.dart, googleapis_auth/lib/src/oauth2_flows/jwt.dart, googleapis_auth/lib/src/oauth2_flows/metadata_server.dart, googleapis_auth/lib/src/utils.dart
- auth: standardize error handling and include error_description if present
- auth: DRY up response -> JSON decoding
=> auth fixes

googleapis_auth/CHANGELOG.md, googleapis_auth/lib/auth_browser.dart, googleapis_auth/lib/auth_io.dart, googleapis_auth/lib/src/exceptions.dart, googleapis_auth/lib/src/oauth2_flows/implicit.dart
- Cleanup whitespace and async logic in auth_browser and auth_io
- auth: Added `String? details` to `UserConsentException`
=> root lib cleanup

discoveryapis_generator/lib/src/dart_api_library.dart, discoveryapis_generator/lib/src/namer.dart, discoveryapis_generator/test/namer_test.dart, generated/googleapis/README.md, generated/googleapis/example/main.dart, generated/googleapis_beta/README.md, generator/lib/src/package_configuration.dart, resources/README.md, resources/googleapis/examples/main.dart
- Cleanup generated readmes
- Update links and examples for readmes
=> readme cleanup

discoveryapis_commons/CHANGELOG.md, discoveryapis_commons/lib/src/multipart_media_uploader.dart, discoveryapis_commons/pubspec.yaml, test_integration/test/storage_test.dart
Fixes https://github.com/google/googleapis.dart/issues/238
Also add a regression test to the integration suite
=> Support Unicode file names in `MultipartMediaUploader`

_test/expected_identical.dart, _test/expected_nonidentical.dart, _test/lib/messages.dart, _test/rest/toyapi.json, _test_package/lib/toyapi/0_1.dart, _test_package/test/toyapi/0_1_test.dart, discoveryapis_generator/lib/src/dart_api_test_library.dart, discoveryapis_generator/lib/src/dart_schemas.dart, generated/googleapis/CHANGELOG.md, generated/googleapis/lib/datastore/v1.dart, generated/googleapis/lib/drive/v3.dart, generated/googleapis/lib/firestore/v1.dart, generated/googleapis/lib/script/v1.dart, generated/googleapis/test/drive/v3_test.dart, generator/lib/src/package_configuration.dart, resources/googleapis/CHANGELOG.md, test_integration/bin/drive_file_properties.dart, test_integration/lib/test_integration.dart, test_integration/test/firestore_test.dart
- Tiny cleanup
- Add one-off logic to handle important cases with null values
=> i211 firestore null type

_test/expected_nonidentical.dart, _test_package/lib/toyapi/0_1.dart, _test_package/test/toyapi/0_1_test.dart, config.yaml, discoveryapis_generator/lib/src/dart_api_test_library.dart, discoveryapis_generator/lib/src/dart_schema_types.dart, generated/googleapis/README.md, generated/googleapis/lib/datastore/v1.dart, generated/googleapis/lib/firestore/v1.dart, generated/googleapis/lib/script/v1.dart, generated/googleapis/lib/src/user_agent.dart, generated/googleapis/pubspec.yaml, generated/googleapis/test/datastore/v1_test.dart, generated/googleapis/test/firestore/v1_test.dart, generated/googleapis/test/script/v1_test.dart, generated/googleapis_beta/README.md, generated/googleapis_beta/lib/src/user_agent.dart, generated/googleapis_beta/pubspec.yaml, resources/googleapis/CHANGELOG.md
=> fixes #291

discovery/googleapis/firestore__v1.json, generated/googleapis/CHANGELOG.md, generated/googleapis/lib/firestore/v1.dart, generated/googleapis/test/firestore/v1_test.dart, overrides/i303.diff, resources/googleapis/CHANGELOG.md
Fixes https://github.com/google/googleapis.dart/issues/303
=> Fix Firestore runQuery issue

discovery/googleapis/chromemanagement__v1.json, discovery/googleapis_beta/analyticsadmin__v1alpha.json, generated/googleapis/README.md, generated/googleapis/lib/chromemanagement/v1.dart, generated/googleapis_beta/README.md, generated/googleapis_beta/lib/analyticsadmin/v1alpha.dart, overrides/i322.diff
chromemanagement v1
analyticsadmin v1alpha
towards https://github.com/google/googleapis.dart/issues/322
=> Fix a couple of http lints causing pub.dev score drops

.gitignore, googleapis_auth/CHANGELOG.md, googleapis_auth/lib/googleapis_auth.dart, googleapis_auth/lib/src/known_uris.dart, googleapis_auth/lib/src/oauth2_flows/auth_code.dart, googleapis_auth/lib/src/oauth2_flows/authorization_code_grant_abstract_flow.dart, googleapis_auth/lib/src/service_account_credentials.dart, googleapis_auth/test/oauth2_flows/auth_code_test.dart, test_integration/bin/simple_oauth.dart, test_integration/lib/test_integration.dart
- test_integration: smarter about requested scopes
- test_integration: more specific about the client type
- auth: eliminate the extra API call for scopes
=> dart dev search console fun

googleapis_auth/README.md
Adding a brief summary of the helpful discussion in #292 to googleapis_auth README
=> Update googleapis_auth README

.github/workflows/dart.yml, tool/ci.sh
Closes https://github.com/google/googleapis.dart/pull/359
Closes https://github.com/google/googleapis.dart/pull/360
=> Latest actions via latest mono_repo

test_integration/pubspec.yaml, test_integration/web/drive.html, test_integration/web/drive_demo.dart
We could imagine adding some helpers here, too.
Closes https://github.com/google/googleapis.dart/issues/366
=> Add a sample showing an implemenation for google/googleapis.dart#366

config.yaml, discovery/googleapis/firebaseremoteconfig__v1.json, discovery/googleapis/photoslibrary__v1.json, generated/googleapis/CHANGELOG.md, generated/googleapis/README.md, generated/googleapis/lib/firebaseremoteconfig/v1.dart, generated/googleapis/lib/photoslibrary/v1.dart, generated/googleapis/lib/shared.dart, generated/googleapis/lib/src/user_agent.dart, generated/googleapis/pubspec.yaml, generated/googleapis/test/firebaseremoteconfig/v1_test.dart, generated/googleapis/test/photoslibrary/v1_test.dart, generator/lib/googleapis_generator.dart, generator/lib/src/package_configuration.dart, resources/googleapis/CHANGELOG.md, tool/local_rebuild.sh
- generator: remove dead code
- generator: tighter null-safety
- Add support for configuring additional APIs, add firebaseremoteconfig
- update usage of `pub` command
- googleapis: added photoslibrary:v1
=> i382 firebase remote config

discovery/googleapis/chromepolicy__v1.json, discovery/googleapis/sts__v1.json, generated/googleapis/README.md, generated/googleapis/lib/chromepolicy/v1.dart, generated/googleapis/lib/sts/v1.dart, overrides/i322.diff
Related to https://github.com/google/googleapis.dart/issues/322
=> Fix two more http URIs in docs

overrides/i411.diff
=> Follow-up to PR #412

config.yaml, discovery/googleapis/firestore__v1.json, generated/googleapis/CHANGELOG.md, generated/googleapis/README.md, generated/googleapis/lib/firestore/v1.dart, generated/googleapis/lib/src/user_agent.dart, generated/googleapis/pubspec.yaml, generated/googleapis/test/firestore/v1_test.dart, overrides/i303.diff, resources/googleapis/CHANGELOG.md
Fixes https://github.com/google/googleapis.dart/issues/303
=> Fix firestore API

.github/workflows/dart.yml, _test/mono_pkg.yaml, _test_package/mono_pkg.yaml, _test_package/pubspec.yaml, config.yaml, discoveryapis_commons/mono_pkg.yaml, discoveryapis_generator/lib/src/pubspec.dart, discoveryapis_generator/mono_pkg.yaml, generated/googleapis/CHANGELOG.md, generated/googleapis/README.md, generated/googleapis/lib/src/user_agent.dart, generated/googleapis/mono_pkg.yaml, generated/googleapis/pubspec.yaml, generated/googleapis_beta/CHANGELOG.md, generated/googleapis_beta/mono_pkg.yaml, generated/googleapis_beta/pubspec.yaml, generator/mono_pkg.yaml, googleapis_auth/mono_pkg.yaml, resources/googleapis/CHANGELOG.md, resources/googleapis/_mono_pkg.yaml, resources/googleapis_beta/CHANGELOG.md, resources/googleapis_beta/_mono_pkg.yaml, resources/test_pkg_mono_pkg.yaml, test_integration/mono_pkg.yaml, tool/ci.sh
use new pubspec mono_repo feature
Closes https://github.com/google/googleapis.dart/pull/437
=> Latest mono_repo, require Dart 2.17 in all packages

googleapis_auth/CHANGELOG.md, googleapis_auth/lib/auth_browser.dart, googleapis_auth/lib/src/authentication_exception.dart, googleapis_auth/lib/src/browser_utils.dart, googleapis_auth/lib/src/exceptions.dart, googleapis_auth/lib/src/oauth2_flows/implicit.dart, googleapis_auth/lib/src/typedefs.dart, googleapis_auth/test/oauth2_flows/implicit/gapi_load_failure_test.dart
- googleapis_auth: inclusive language
- googleapis_auth: refactor browser auth JS loading logic for reuse
=> auth exception

.github/workflows/dart.yml, _test/mono_pkg.yaml, _test_package/mono_pkg.yaml, discoveryapis_commons/mono_pkg.yaml, discoveryapis_generator/mono_pkg.yaml, generated/googleapis/mono_pkg.yaml, generated/googleapis_beta/mono_pkg.yaml, generator/mono_pkg.yaml, googleapis_auth/CHANGELOG.md, googleapis_auth/lib/src/auth_functions.dart, googleapis_auth/lib/src/auth_http_utils.dart, googleapis_auth/lib/src/http_client_base.dart, googleapis_auth/mono_pkg.yaml, resources/googleapis/_mono_pkg.yaml, resources/googleapis_beta/_mono_pkg.yaml, resources/test_pkg_mono_pkg.yaml, test_integration/lib/test_integration.dart, test_integration/mono_pkg.yaml, test_integration/web/drive.html, test_integration/web/drive_demo.dart, test_integration/web/google_identity_demo.dart, test_integration/web/google_identity_demo.html, test_integration/web/implicit_browser_flow.dart, test_integration/web/implicit_browser_flow.html, test_integration/web/index.html, test_integration/web/web_shared.dart, tool/ci.sh
- test_integration: cleanup demos, use new auth flow for drive demo
- googleapis_auth: authenticatedClient add optional closeUnderlyingClient
- Add GIS web demo, refactor the other web samples a bit
=> better browser integration

discoveryapis_commons/CHANGELOG.md, discoveryapis_commons/lib/src/api_requester.dart, discoveryapis_commons/lib/src/multipart_media_uploader.dart, discoveryapis_commons/lib/src/request_impl.dart, discoveryapis_commons/lib/src/resumable_media_uploader.dart, discoveryapis_commons/lib/src/utils.dart, discoveryapis_commons/pubspec.yaml, test_integration/web/drive_demo.dart
Fixes https://github.com/google/googleapis.dart/issues/462
=> [commons] Handle different cases in response header keys

discoveryapis_commons/CHANGELOG.md, discoveryapis_commons/pubspec.yaml
fixes https://github.com/google/googleapis.dart/issues/478
=> [commons] prepare v1.0.5 release

.github/workflows/dart.yml, tool/ci.sh
=> Latest GitHub actions

discovery/googleapis/firebaseremoteconfig__v1.json, generated/googleapis/lib/firebaseremoteconfig/v1.dart, generated/googleapis/lib/shared.dart, generated/googleapis/test/firebaseremoteconfig/v1_test.dart, overrides/i488.diff, test_integration/test/firebase_remote_config_test.dart
Fixes https://github.com/google/googleapis.dart/issues/488
=> Fix Firebase config defaults return value

.github/workflows/verify_examples.yml
=> blast_repo fixes

test_integration/pubspec.yaml, test_integration/tool/run_server.dart
- test_integration: smarter usage of Dart CLI
- test_integration: support the latest pkg:build_web_compilers
=> integration cleanup

.github/workflows/dart.yml, tool/ci.sh
Closes https://github.com/google/googleapis.dart/pull/511
=> Latest actions/cache

.github/workflows/dart.yml, tool/ci.sh
- api updates
- latest CI actions
=> ci updates

config.yaml, discovery/googleapis/identitytoolkit__v1.json, discovery/googleapis/identitytoolkit__v2.json, discoveryapis_generator/lib/src/client/client_schemas.dart, discoveryapis_generator/lib/src/dart_resources.dart, discoveryapis_generator/lib/src/dart_schema_types.dart, discoveryapis_generator/lib/src/dart_schemas.dart, discoveryapis_generator/lib/src/unused_logic.dart, generated/googleapis/CHANGELOG.md, generated/googleapis/README.md, generated/googleapis/lib/identitytoolkit/v1.dart, generated/googleapis/lib/identitytoolkit/v2.dart, generated/googleapis/lib/shared.dart, generated/googleapis/lib/src/user_agent.dart, generated/googleapis/pubspec.yaml, generated/googleapis/test/identitytoolkit/v1_test.dart, generated/googleapis/test/identitytoolkit/v2_test.dart, resources/googleapis/CHANGELOG.md
=> Adding identitytoolkit v1 and v2 APIs

_test_package/pubspec.yaml, config.yaml, discoveryapis_generator/lib/src/pubspec.dart, generated/googleapis/CHANGELOG.md, generated/googleapis/README.md, generated/googleapis/lib/src/user_agent.dart, generated/googleapis/pubspec.yaml, generated/googleapis_beta/pubspec.yaml, resources/googleapis/CHANGELOG.md
https://github.com/google/googleapis.dart/pull/548
=> Follow-up to actually enable latest pkg:http

.github/workflows/dart.yml, _test/pubspec.yaml, _test_package/pubspec.yaml, analysis_options.yaml, config.yaml, discoveryapis_commons/CHANGELOG.md, discoveryapis_commons/pubspec.yaml, discoveryapis_generator/bin/generate.dart, discoveryapis_generator/lib/src/pubspec.dart, discoveryapis_generator/pubspec.yaml, generated/googleapis/CHANGELOG.md, generated/googleapis/pubspec.yaml, generated/googleapis_beta/CHANGELOG.md, generated/googleapis_beta/README.md, generated/googleapis_beta/lib/src/user_agent.dart, generated/googleapis_beta/pubspec.yaml, generator/bin/generate.dart, generator/pubspec.yaml, googleapis_auth/CHANGELOG.md, googleapis_auth/lib/src/oauth2_flows/implicit.dart, googleapis_auth/pubspec.yaml, resources/googleapis/CHANGELOG.md, resources/googleapis_beta/CHANGELOG.md, test_integration/bin/desktop_auth_server.dart, test_integration/pubspec.yaml
Small tweaks to switch statements
=> Require Dart 3 across packages

discoveryapis_generator/CHANGELOG.md, discoveryapis_generator/lib/src/namer.dart, discoveryapis_generator/pubspec.yaml, discoveryapis_generator/test/namer_test.dart, generated/googleapis/README.md, generated/googleapis_beta/README.md, generator/lib/src/package_configuration.dart
=> Update to readme documentation

config.yaml, generated/googleapis_beta/CHANGELOG.md, generated/googleapis_beta/README.md, generated/googleapis_beta/lib/src/user_agent.dart, generated/googleapis_beta/pubspec.yaml, resources/googleapis_beta/CHANGELOG.md
Fixes https://github.com/google/googleapis.dart/issues/591
=> Publish new googleapis_beta

config.yaml, discovery/googleapis/datamigration__v1.json, discovery/googleapis/firebasedynamiclinks__v1.json, discovery/googleapis/iam__v2.json, discovery/googleapis/monitoring__v3.json, discovery/googleapis/servicecontrol__v1.json, discovery/googleapis/servicecontrol__v2.json, discovery/googleapis/speech__v2.json, generated/googleapis/CHANGELOG.md, generated/googleapis/README.md, generated/googleapis/lib/monitoring/v3.dart, generated/googleapis/lib/shared.dart, generated/googleapis/lib/speech/v1.dart, generated/googleapis/lib/speech/v2.dart, generated/googleapis/test/speech/v2_test.dart, resources/googleapis/CHANGELOG.md
Fixes https://github.com/google/googleapis.dart/issues/603
=> Add speech v2

generated/googleapis/README.md, generated/googleapis_beta/README.md, generator/lib/src/package_configuration.dart
Fixes https://github.com/google/googleapis.dart/issues/599
=> Fix pub URIs

test_integration/bin/slide_notes.dart, test_integration/lib/test_integration.dart
retry requests
Better text output
Cleanup code
populate title correctly
skip skipped slides
=> [test_integration/slide_notes] improvements to demo app

discoveryapis_commons/CHANGELOG.md, discoveryapis_commons/lib/src/multipart_media_uploader.dart, discoveryapis_commons/pubspec.yaml, discoveryapis_commons/test/discoveryapis_commons_test.dart
Fixes https://github.com/google/googleapis.dart/issues/636
=> commons: Support streaming media from `Stream<Uint8List>`

googleapis_auth/lib/src/oauth2_flows/token_model.dart, googleapis_auth/pubspec.yaml
...and a bunch of extra console.log messages
=> auth: drop pkg:web dependency

googleapis_auth/CHANGELOG.md, googleapis_auth/README.md, googleapis_auth/example/example.dart, googleapis_auth/pubspec.yaml
Fixes https://github.com/google/googleapis.dart/issues/671
=> auth: prepare v2 release
